version: "3"
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    ports:
      - "9000:9000"
    extra_hosts:
      - host.docker.internal:host-gateway

  phpunit:
    image: php:8.2-cli
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    entrypoint: ["vendor/bin/phpunit"]
